Update window.yml

diff --git a/.github/workflows/window.yml b/.github/workflows/window.yml
--- a/.github/workflows/window.yml
+++ b/.github/workflows/window.yml
@@ -80,11 +80,16 @@ jobs:
         shell: powershell
         id: osquery_version
         run: |
-          cd ${{ steps.build_paths.outputs.SOURCE }}
-          $osquery_version=$(git describe --tags --abbrev=0)
+          cd ${{ steps.build_paths.outputs.REL_SOURCE }}
+          $osquery_version = $(git describe --tags --abbrev=0 2>&1)
+      
+          if ($LASTEXITCODE -ne 0) {
+              echo "Error: $osquery_version"
+              exit 1
+          }
+      
+          echo "VALUE=$osquery_version" >> ${{ env.GITHUB_OUTPUT }}
 
-
-          echo "VALUE=$osquery_version" >> $env:GITHUB_OUTPUT
 
           
           
